name: pa2_deer_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - rasterio
  - osmnx
  - pyrosm
  - scikit-image
  - matplotlib
  - requests
  - shapely
  - libgdal
  - pip